import { error_response } from "../helpers/send.response";

export const sign_up=async(req,res)=>{
    try {
        
    } catch (error) {
    return error_response(error.message, res);

    }
}